spring:
  application:
    name: titanic
  # SQL
  datasource:
    url: jdbc:postgresql://localhost/titanic
    username: postgres
    password: 12345

  jpa:
    generate-ddl: true
    #show-sql: true #просмотр сгенерированных запросов
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

fileUrl: https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv

